# Generated by Django 3.0.7 on 2023-04-04 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_total', models.PositiveIntegerField(verbose_name='총 가격')),
                ('address', models.CharField(max_length=300, verbose_name='배송지 주소')),
                ('collection_name', models.CharField(max_length=100, verbose_name='컬렉션명')),
                ('recipient', models.CharField(max_length=10, verbose_name='받는 사람')),
                ('recipient_phone', models.CharField(max_length=15, verbose_name='수령인 연락처')),
                ('delivery_message', models.TextField(blank=True, verbose_name='배송 요청사항')),
                ('period', models.CharField(choices=[('1W', '1주'), ('2W', '2주'), ('3W', '3주'), ('1M', '1달'), ('2M', '2달'), ('3M', '3달')], max_length=2, verbose_name='주기')),
                ('isValid', models.BooleanField(default=True, verbose_name='유효성')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='수량')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '주문상품',
                'verbose_name_plural': '주문상품',
            },
        ),
        migrations.CreateModel(
            name='Ordering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='주문')),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderProduct', verbose_name='주문 상품')),
            ],
        ),
    ]
